### ISSUE TITLE
User can view products

### ISSUE THREAD

**Issue by qnpham** [quannampham/final-project#1]
## ⚙️ Feature

> ##### The user will be able to view the products available

## 📐 Functionality

> ##### The user will be able to see products on the home page

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2022-11-07 at 6 11 23 PM](https://user-images.githubusercontent.com/84756451/200458030-1d4d6999-629e-4e40-b7b4-c6178d94eb42.png)
![Screen Shot 2022-11-07 at 6 11 35 PM](https://user-images.githubusercontent.com/84756451/200458042-be349696-2a43-43e6-ac73-ae9efa514f32.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [x] create and import `schema.sql` 
- [x] create and import `data.sql`

### ☁️ Server Tasks

- [x] create route for GET request
- [x] create api
- [x] Test with HTTPie

### ⚡ Client Tasks

- [x] create mobile navbar
- [x] create mobile carousel
- [x] create mobile product list
- [x] create desktop navbar
- [x] create desktop carousel
- [x] create desktop product list

### 🧑‍⚕️ Clean Up Tasks
 
- [x] ensure resizing window works
- [x] cleanup mobile view
- [x] cleanup tablet view
- [x] cleanup desktop view
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
