### ISSUE TITLE
User can view checkout confirmation

### ISSUE THREAD

**Issue by qnpham** [quannampham/final-project#10]
## ⚙️ Feature

> ##### Upon checking out successfully, the user is shown a success confirmation screen

## 📐 Functionality

> ##### If the user's information is valid, then the order processes and the success confirmation screen is shown.

## 🖼️ Wireframes

> 
![Screen Shot 2022-11-08 at 9 56 31 AM](https://user-images.githubusercontent.com/84756451/200640066-544a90c2-852b-483d-acd5-531900c1fef2.png)
![Screen Shot 2022-11-08 at 9 56 11 AM](https://user-images.githubusercontent.com/84756451/200640077-cfb1472b-f496-4e36-a718-f3ba9430c8f1.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ⚡ Client Tasks

- [x] create mobile view
- [x] add media queries for tablet
- [x] add media queries for desktop
- [x] update logo in navbar to change window.location instead of hash

### 🧑‍⚕️ Clean Up Tasks

- [ ] ... 
- [ ] ...
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
