### ISSUE TITLE
User can search for products

### ISSUE THREAD

**Issue by qnpham** [quannampham/final-project#2]
## ⚙️ Feature

> The user will be able to search for a product

## 📐 Functionality

> The user will be able to search using keywords to find a product

## 🖼️ Wireframes

> 
![Screen Shot 2022-11-07 at 6 15 27 PM](https://user-images.githubusercontent.com/84756451/200458562-4b7dffa3-ccd7-4be4-8501-6089bb11d6a5.png)
![Screen Shot 2022-11-07 at 6 17 04 PM](https://user-images.githubusercontent.com/84756451/200458703-0ee99de6-89e2-4969-a390-13da5bbc28c6.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ⚡ Client Tasks

- [ ] create search bar on home page
- [ ] create search view search bar
- [ ] create search result
- [ ] add text for when no result is found
- [ ] add media queries for tablet
- [ ] add media queries for desktop 

### 🧑‍⚕️ Clean Up Tasks

- [ ] ... 
- [ ] ...
- [ ] ensure clicking on a game displays detailed view
- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
