### ISSUE TITLE
User can view details of a product

### ISSUE THREAD

**Issue by qnpham** [quannampham/final-project#5]
## ⚙️ Feature

> The user will be able to view a product page

## 📐 Functionality

> The user will be able to details of a product by clicking on it's thumbnail

## 🖼️ Wireframes

> 
![Screen Shot 2022-11-07 at 6 24 41 PM](https://user-images.githubusercontent.com/84756451/200459811-f1635c09-caa2-425f-a09b-ef3e25a0d79b.png)
![Screen Shot 2022-11-07 at 6 24 59 PM](https://user-images.githubusercontent.com/84756451/200459818-fb538949-f5f5-4acd-bbad-95ae156cc650.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [x] add 2 games

### ☁️ Server Tasks

- [x] make a route to get detailed data of a game
- [x] make a route for screenshots
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Create mobile carousel
- [x] create mobile text
- [x] create "ADD TO CART" button
- [x] create tablet media queries
- [x] create screenshot scroll
- [x] create desktop text media queries

### 🧑‍⚕️ Clean Up Tasks

- [x] ... 
- [x] ...
- [x] create hashroute
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
