### ISSUE TITLE
User can add product to cart

### ISSUE THREAD

**Issue by qnpham** [quannampham/final-project#6]
## ⚙️ Feature

> The user will be able to add a product to their cart

## 📐 Functionality

> Once the user clicks "ADD TO CART" the item will be added to cart and the cart view will show.

## 🖼️ Wireframes

> 
![Screen Shot 2022-11-07 at 6 28 42 PM](https://user-images.githubusercontent.com/84756451/200460375-7749dc08-7078-42a2-bacf-022939e62e45.png)
![Screen Shot 2022-11-07 at 6 30 22 PM](https://user-images.githubusercontent.com/84756451/200460473-7b173865-83b3-4201-80b9-1b63e3419243.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [x] add a column for user token to cart table

### ☁️ Server Tasks

- [x] make a POST route for token and cartid
- [x] if no token, then create a new token and cartId and send token back to user
- [x] verify token and send back user data
- [x] make a route to add an item to cart

### ⚡ Client Tasks

- [x] make condition to verify that there is a token in localstorage
- [x] if there is none, then send a post request to api to create a new token
- [x] send token to api to verify and get cart items
- [x] store user data
- [x] create mobile cart view
- [x] add tablet media queries
- [x] add desktop media queries
- [x] add hashrouting
- [x] if the user adds an item to cart, send a POST request to api update database

### 🧑‍⚕️ Clean Up Tasks

- [ ] ... 
- [ ] ...
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
