### ISSUE TITLE
User can edit quantity in cart

### ISSUE THREAD

**Issue by qnpham** [quannampham/final-project#7]
## ⚙️ Feature

> The user will be able to adjust how the quantity of a product in their cart

## 📐 Functionality

> The user will be press "-" or "+" to adjust quantity. If quantity is less than one it gets removed.

## 🖼️ Wireframes

> 
![Screen Shot 2022-11-08 at 9 11 23 AM](https://user-images.githubusercontent.com/84756451/200630745-1c32d1ee-552b-4c4b-a328-a1032ce50bc5.png)

![Screen Shot 2022-11-08 at 9 10 31 AM](https://user-images.githubusercontent.com/84756451/200630523-79f78b79-ccb1-4c60-8d4d-45ec021a41e4.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ☁️ Server Tasks

- [x] create a route to set quantity
- [x] create a route to delete

### ⚡ Client Tasks

- [x] create function to increment
- [x] create function to decrement
- [x] create function to delete
- [x] make logic, if quantity is zero, then run delete handler function

### 🧑‍⚕️ Clean Up Tasks

- [x] ... 
- [x] ...
- [x] refactor to not use old increment quantity function
- [ ] add event listeners to checkout page
- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
