### ISSUE TITLE
User can view checkout page

### ISSUE THREAD

**Issue by qnpham** [quannampham/final-project#8]
## ⚙️ Feature

> The user will be able to view checkout page

## 📐 Functionality

> The user will click "CHECKOUT" in the cart view. Doing so will redirect the user to the checkout page.

## 🖼️ Wireframes

> 
![Screen Shot 2022-11-08 at 9 13 27 AM](https://user-images.githubusercontent.com/84756451/200631191-dc8aaae9-c413-4565-91b6-46b6fe79decc.png)
![Screen Shot 2022-11-08 at 9 13 45 AM](https://user-images.githubusercontent.com/84756451/200631202-5a7a215b-91ec-4e96-b603-04538d8b61b2.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ⚡ Client Tasks

- [x] add hashrouting
- [x] Create mobile cart
- [x] create total
- [x] create mobile checkout button
- [x] add media queries for tablet
- [x] add media queries for desktop

### 🧑‍⚕️ Clean Up Tasks

- [ ] ... 
- [ ] ...
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
