### ISSUE TITLE
User can checkout

### ISSUE THREAD

**Issue by qnpham** [quannampham/final-project#9]
## ⚙️ Feature

> The user's cart and order will be processed

## 📐 Functionality

> Once the user click "CHECKOUT" again they will be brought to a form. Filling out the form and pressing "CHECKOUT" again will process their order.

## 🖼️ Wireframes

> 
![Screen Shot 2022-11-08 at 9 15 50 AM](https://user-images.githubusercontent.com/84756451/200631654-5fc3bee7-3389-4e4d-8d8e-93bd54651758.png)
![Screen Shot 2022-11-08 at 9 16 02 AM](https://user-images.githubusercontent.com/84756451/200631672-e3bd36b5-a829-4c0d-a208-67458576b6fc.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ☁️ Server Tasks

- [x] setup stripe
- [x] create a post route to make orders

### ⚡ Client Tasks

- [x] create hashroute
- [x] create mobile view
- [x] ensure that submitting an order works
- [x] make media queries for tablet
- [x] make media queries for desktop

### 🧑‍⚕️ Clean Up Tasks

- [ ] ... 
- [ ] ...
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
